apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize

resources:
  - secrets/repo-creds-github.yaml
  - secrets/repo-ghcr-platform-charts.yaml
  - secrets/ghcr-pull.yaml