apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "xxx"
        }
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "2"
imagePullSecrets:
  - name: ghcr-pull
