apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  url: https://github.com/BacktotheBone
  type: git
  githubAppID: "xxx"
  githubAppInstallationID: "xxx"
  githubAppPrivateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
